//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Su_Dagitim_1_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        public int ID { get; set; }
        public string Plaka { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public Nullable<int> CalisanID { get; set; }
    }
}
