//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Su_Dagitim_1_0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Su_ManagerEntities1 : DbContext
    {
        public Su_ManagerEntities1()
            : base("name=Su_ManagerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arac> Arac { get; set; }
        public DbSet<Calisan> Calisan { get; set; }
        public DbSet<Calisma> Calisma { get; set; }
        public DbSet<Musteri> Musteri { get; set; }
    }
}
